// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	CommentID int64
	Text      string
	UserID    int64
	PageID    int64
	ReplyTo   pgtype.Int8
	Date      pgtype.Timestamp
}

type Page struct {
	PageID    int64
	Name      string
	Path      string
	WebsiteID int64
}

type User struct {
	UserID   int64
	Name     string
	Email    string
	Password string
}

type Website struct {
	WebsiteID int64
	Name      string
	Url       string
}
